---
- hosts: all
  gather_facts: true
  tasks:
  - name: Install packages
    yum: pkg={{item}} state=installed
    with_items:
     - epel-release
    become: true

  - name: Install packages
    yum: pkg={{item}} state=installed
    with_items:
     - python-pip   
    become: true
 
  - name: Unarchive a file that needs to be downloaded (added in 2.0)
    unarchive:
      src: "{{ item }}"
      dest: /home/vagrant
      remote_src: yes
    with_items:
      - https://github.com/prometheus/prometheus/releases/download/v2.0.0/prometheus-2.0.0.linux-amd64.tar.gz
      - https://github.com/prometheus/node_exporter/releases/download/v0.15.1/node_exporter-0.15.1.linux-amd64.tar.gz
  - name: Copy the Config to read from node_exporter
    copy: 
      src: prometheus.yml 
      dest: /home/vagrant/prometheus-2.0.0.linux-amd64/ 
  - name: Start prometheus Services
    shell: cd /home/vagrant/prometheus-2.0.0.linux-amd64 ; nohup ./prometheus >/dev/null 2>&1 & sleep 1
  - name: Start Node exporter
    shell: nohup /home/vagrant/node_exporter-0.15.1.linux-amd64/node_exporter &
  - name: Install Prometheus Python client
    pip:
      name: prometheus_client
    become: true

  - name: Start the Custom Gauge exporter app
    shell: nohup python /vagrant/gauge-example.py &